name: Update Redtube Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'   # Her 4 saatte bir

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3

      - name: Run redtube Script
        run: python redtube.py
        env:
          ENCRYPTED_PLAYLIST_URL: ${{ secrets.ENCRYPTED_PLAYLIST_URL }}

      - name: Commit & Push Changes
        run: |
          git config --local user.email "botechred@gmail.com"
          git config --local user.name "botechred"      
          
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git add -A
            git commit -m "Update redtube playlist - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
            echo "✅ Playlist successfully updated"
          fi
